'use client';

import React from 'react';

interface SplashScreenProps {
  onNewGame: () => void;
  isLoading?: boolean;
}

export const SplashScreen: React.FC<SplashScreenProps> = ({ 
  onNewGame, 
  isLoading = false 
}) => {
  return (
    <div className="flex flex-col items-center justify-center h-screen bg-gray-900 text-white">
      <div className="text-center">
        <h1 className="text-6xl font-bold mb-8 text-purple-400 animate-pulse">
          Ethereal Arena
        </h1>
        
        <div className="text-xl mb-12 max-w-lg">
          <p className="mb-4">
            Welcome to a mystical card battle where your fate is determined by the cosmic forces
            and the strength of your deck.
          </p>
          <p>
            Each card is uniquely generated by AI, ensuring no two games are ever the same.
          </p>
        </div>
        
        <button
          onClick={onNewGame}
          disabled={isLoading}
          className={`
            px-8 py-4 text-xl rounded-lg font-semibold
            transition-all duration-300 transform hover:scale-105
            ${isLoading 
              ? 'bg-gray-600 cursor-not-allowed' 
              : 'bg-purple-600 hover:bg-purple-500 active:bg-purple-700'
            }
          `}
        >
          {isLoading ? (
            <>
              <span className="animate-spin inline-block mr-2">⟳</span>
              Creating Game...
            </>
          ) : (
            'New Game'
          )}
        </button>
      </div>
    </div>
  );
};